changes_app_release_process_CPLP-818
catenax-ng/tx-portal-frontend pull request #102
Opened 2023-01-17 14:21 UTC by lavanya-bmw

2023-01-18 05:49 UTC, nidhigarg-bmw commented
@lavanya-bmw Just noticed, one code smell can be fixed ?

2023-01-18 06:03 UTC, manojava-gk reviewed
Type related comments

2023-01-18 06:03 UTC, manojava-gk commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +      const defaultUseCaseIds: any = useCasesList?.filter((item) =>
can we specify a type instead of any?

2023-01-18 06:03 UTC, manojava-gk commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +      const defaultAppLanguages: any = appLanguagesList?.filter((item) =>
can we specify a type instead of any?

2023-01-19 07:29 UTC, oyo approved these changes
lgtm

2023-01-19 07:50 UTC, oyo requested changes
linter failure

2023-01-19 08:06 UTC, jjeroch submitted a review, later dismissed

2023-01-19 16:14 UTC, oyo approved these changes
lgtm now

2023-01-19 16:14 UTC, merged