First commit on checklist related updates
catenax-ng/tx-portal-frontend pull request #121
Opened 2023-01-20 10:57 UTC by manojava-gk

2023-01-23 06:51 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckListStatusOverlay.tsx
> +  // const [loading, setLoading] = useState<boolean>(false)
is this needed to give static loading value ?

2023-01-23 06:51 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckListStatusOverlay.tsx
> +            tungHa' taS, ghor jatIh wanI' pab wuv qugh ghoma' jIv. Saqghom
Add into translation file

2023-01-23 06:51 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/index.tsx
> +          onChipButtonSelect={(selected: ProgressButtonsProps, row: any) =>
is this will be any datatype ?

2023-01-23 07:39 UTC, manojava-gk commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckListStatusOverlay.tsx
> +  // const [loading, setLoading] = useState<boolean>(false)
Will use useState once APIs are ready

2023-01-23 07:39 UTC, manojava-gk commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckListStatusOverlay.tsx
> +            tungHa' taS, ghor jatIh wanI' pab wuv qugh ghoma' jIv. Saqghom
Its a dummy value that I have used. Will check @jjeroch  for the appropriate content.

2023-01-23 07:41 UTC, manojava-gk commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/index.tsx
> +          onChipButtonSelect={(selected: ProgressButtonsProps, row: any) =>
Not sure about the data that is needed for the next step. Will update once I have clear picture on API details

2023-01-23 14:37 UTC, oyo requested changes
code has a big improvement potential

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckListStatusOverlay.tsx
> +        <Divider sx={{ borderBottomStyle: 'dashed' }} />
Using a Divider component is not a good practice unless it has a special purpose. This is style and can usually avoid it easily by adding a `border-bottom` or `border-top` to one of the enclosing nodes

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckListStatusOverlay.tsx
> +        <Divider sx={{ borderBottomStyle: 'dashed' }} />
see other divider comment

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckListStatusOverlay.tsx
> +        <Divider sx={{ borderBottomStyle: 'dashed' }} />
see other divider comment

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/RequestList/index.tsx
> +  onChipButtonSelect?: any
we should try to avoid any since we are using typescript. if the type is not clear yet we can at least declare an empty interface or function as placeholder

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckListStatusOverlay.tsx
> +import { Divider } from '@mui/material'
please no Divider component - use css attributes border-bottom or border-top of the enclosing nodes

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/index.tsx
> +  const onChipButtonSelect = (selected: ProgressButtonsProps, row: any) => {
row should not be `any`. at least you are accessing some attribute `applicationCheckList`. So define a type or interface for this.

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/index.tsx
> +          onChipButtonSelect={(selected: ProgressButtonsProps, row: any) =>
please try to avoid the use of `any`. In cases where we really don't know the type we can at least declare an empty type or interface where we can add attributes later

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx
> +  onChipButtonSelect?: (button: ProgressButtonsProps, row: any) => void
row: any

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx
> +      renderCell: ({ row }: { row: ApplicationRequest }) => (
here the type of row is `ApplicationRequest`. seems like we can use that for all `any` types in the other functions

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/shared/basic/CheckList/index.tsx
> +    // eslint-disable-next-line
linter checks should only be disabled in very special cases. I've seen these far too often in recent code.

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/shared/basic/CheckList/index.tsx
> +      case 'REGISTRATION_VERIFICATION':
define a enum for all those strings and then use these because this way we have IDE support

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/shared/basic/CheckList/index.tsx
> +        return 'Data Validation'
no translation for strings

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/shared/basic/CheckList/index.tsx
> +  }
the purpose of this entire method is unclear. we can replace this by:
`t('path.to.${typeId}')`
(replace ' with backticks)

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/shared/basic/CheckList/index.tsx
> +  statusId: 'IN_PROGRESS' | 'TO_DO' | 'DONE' | 'FAILED'
better define a string enum type because later we are using these values in `switch` statements as string and lose IDE support

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/components/shared/basic/CheckList/index.tsx
> +  }
this looks like way too much redundancy. create a function that receives only the varying params and returns the object customized to these

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/features/admin/applicationRequestApiSlice.ts
> +          fetchArgs.args.statusFilter === 'All'
another hard coded string instead of a string enum type. If someone renames this to 'all' or 'ALL' it will fail

2023-01-23 14:37 UTC, oyo commented on cx-portal/src/features/admin/applicationRequestApiSlice.ts
> +          fetchArgs.args.statusFilter === 'All'
hard coded string comparison

2023-01-24 05:47 UTC, manojava-gk commented on cx-portal-shared-components/src/components/basic/Table/index.tsx
> +          '&.MuiDataGrid-root .MuiDataGrid-columnHeader:focus, &.MuiDataGrid-root .MuiDataGrid-cell:focus, &.MuiDataGrid-root .MuiDataGrid-cell:focus-within':
Will demonstrate the purpose of this. Let me know your input to avoid these override css

2023-01-24 05:49 UTC, manojava-gk commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckListStatusOverlay.tsx
> +        '.MuiPaper-root': {
Trying to make it more dynamic in terms of width and matching borderRadius with the design

2023-01-24 05:49 UTC, manojava-gk commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckListStatusOverlay.tsx
> +          '&.MuiDialogActions-root': {
Trying to match with the design

2023-01-25 06:58 UTC, oyo approved these changes
lgtm now

2023-01-25 08:09 UTC, merged