App release process
catenax-ng/tx-portal-frontend pull request #133
Opened 2023-01-24 12:38 UTC by lavanya-bmw

2023-01-25 07:15 UTC, oyo requested changes
some minor suggestions

2023-01-25 07:15 UTC, oyo commented on cx-portal-shared-components/src/components/basic/Dropzone/components/DropPreview.tsx
> +    } else setDeleteStatus({ index: 0, state: false })
this is the same call in `if` and `else` - remove the `else` and put this call after the `if`

2023-01-25 07:15 UTC, oyo commented on cx-portal-shared-components/src/components/basic/Dropzone/components/DropPreview.tsx
> +                isFinished(file) && (
better use a .filter here and then a .map to iterate over the results
`uploadFiles.filter(isFinished).map(....)`

2023-01-25 07:15 UTC, oyo commented on cx-portal-shared-components/src/components/basic/Dropzone/components/DropPreview.tsx
> +                !isFinished(file) && (
better use a .filter here and then a .map to iterate over the results
`uploadFiles.filter(isNotFinished).map(....)`

2023-01-25 07:15 UTC, oyo commented on cx-portal-shared-components/src/components/basic/Dropzone/components/DropPreviewFile.tsx
> +    uploadFile.status !== 'upload_error'
this has been here before but better add a string enum for all the different states. This is more safe than comparing strings.
`enum UploadStatus {`
`   UPLOADING = 'uploading'`
`...`

`uploadFile.status !== UploadStatus.UPLOADING` 
etc...

2023-01-27 08:09 UTC, oyo approved these changes
looks good now

2023-01-27 08:11 UTC, lavanya-bmw commented on cx-portal-shared-components/src/components/basic/Dropzone/components/DropPreview.tsx
> +    } else setDeleteStatus({ index: 0, state: false })
Resolved

2023-01-27 08:11 UTC, lavanya-bmw commented on cx-portal-shared-components/src/components/basic/Dropzone/components/DropPreview.tsx
> +                isFinished(file) && (
Resolved

2023-01-27 08:11 UTC, lavanya-bmw commented on cx-portal-shared-components/src/components/basic/Dropzone/components/DropPreview.tsx
> +                !isFinished(file) && (
Resolved

2023-01-27 08:12 UTC, lavanya-bmw commented on cx-portal-shared-components/src/components/basic/Dropzone/components/DropPreviewFile.tsx
> +    uploadFile.status !== 'upload_error'
Resolved

2023-01-27 08:12 UTC, merged