CPLP 2099 Company data overlay changes
catenax-ng/tx-portal-frontend pull request #177
Opened 2023-02-10 08:40 UTC by manojava-gk

2023-02-13 07:43 UTC, manojava-gk commented
This PR includes these changes

1. Cancel process api method update
2. Min height fix in overlay
3. Registration process info in details overlay

2023-02-13 15:10 UTC, oyo requested changes
some remarks - also change log merge conflict to resolve

2023-02-13 15:10 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/CompanyDetailsHelper.tsx
> +    } else {
else not needed when all previous cases result in a `return`

2023-02-14 07:34 UTC, manojava-gk commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/CompanyDetailsHelper.tsx
> +      )
Thanks Martin, nice concept it is. We should replace our existing approach with this.

2023-02-14 12:03 UTC, nidhigarg-bmw submitted a review, later dismissed
lgtm

2023-02-15 09:20 UTC, oyo requested changes
the conversations are marked as resolved but I can't see the requested changes in the code for example in `CompanyDetailsHelper.tsx`

2023-02-15 10:08 UTC, manojava-gk commented
> the conversations are marked as resolved but I can't see the requested changes in the code for example in `CompanyDetailsHelper.tsx`

Something went wrong. I had done all the changes in a new branch and that PR is also merged here(if you remember, I had asked you to approve without review). Not sure what happened in b/w, I'm not able to find that commit at all. Unfortunately I deleted old local repo folder. I cloned again to fix git pull issues. Now I do not have access to my local changes too. I have to rework on this. Give some time to update the PR

2023-02-16 08:12 UTC, oyo approved these changes
lgtm now

2023-02-16 08:12 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/CompanyDetailsHelper.tsx
> +    (a, b) => b && b.statusId === ProgressStatus.DONE,
this must be `(a, b) => a && b.statusId === ....`

2023-02-16 08:13 UTC, oyo requested changes
one small change - otherwise looks okay

2023-02-16 08:18 UTC, oyo approved these changes

2023-02-16 08:20 UTC, merged