Company subscription  image issue fix
catenax-ng/tx-portal-frontend pull request #208
Opened 2023-02-21 06:14 UTC by manojava-gk

2023-02-21 06:17 UTC, manojava-gk commented
could not get rid of any type as it is from Promise function. Compilation failed by saying unknown[] is not assignable to a type

2023-02-21 07:48 UTC, oyo requested changes
code difficult to read and understand see suggestions to simplify

2023-02-21 07:48 UTC, oyo commented on cx-portal/src/services/CommonService.ts
> +                  }
a cleaner way to write this:
`reader.onload = () => resolve(doNotPickDefaultType ? {...obj_from_else...} : {...obj_from_if...})`

2023-02-21 07:48 UTC, oyo commented on cx-portal/src/components/pages/Organization/index.tsx
> +  const [appSubscribedData, setAppSubscribedData] = useState<any>([])
avoid any - define a type or interface for `appSubscribedData`

2023-02-21 07:48 UTC, oyo commented on cx-portal/src/components/pages/Organization/index.tsx
> +      }) => [
define a type or interface for complex objects

2023-02-21 07:48 UTC, oyo commented on cx-portal/src/components/pages/Organization/index.tsx
> +  }, [data, subscriptionStatus])
this is very difficult to read - better something like (schematic)

`Promise.all(newPromies).then((result) =>
  setAppSubscribedData(
    result
      .flat()
      .map((app: SomeTypeOrInterface) => ({
        ...app,
        subscriptionStatus?.find(...)
      }))
  )
)`

2023-02-21 07:52 UTC, oyo commented on cx-portal/src/components/pages/Organization/index.tsx
> +  const [appSubscribedData, setAppSubscribedData] = useState<any>([])
@manojava-gk just saw your comment on the `any` - I'm going to check out the branch to see

2023-02-21 08:26 UTC, oyo requested changes
one more remark

2023-02-21 08:26 UTC, oyo commented on cx-portal/src/services/CommonService.ts
> +                    !doNotPickDefaultType
instead of
`!condition ? a : b`
better write
`condition ? b : a`

2023-02-21 08:53 UTC, manojava-gk commented on cx-portal/src/services/CommonService.ts
> +                    !doNotPickDefaultType
As value itself has default value as false, I wrote like this. Will update it

2023-02-21 09:28 UTC, nidhigarg-bmw submitted a review, later dismissed

2023-03-06 09:05 UTC, oyo requested changes
Image loading is using the bad design pattern with `Promise.all` - please change. Have a look at ´AppOverviewNew` page how to use

2023-03-06 09:05 UTC, oyo commented on cx-portal/src/components/pages/Organization/index.tsx
> +      const newPromies = CommonService.fetchLeadPictureImage(data, true)
no `Promise.all` for image loading - use the new Image component (see https://jira.catena-x.net/browse/CPLP-2284 )

2023-03-06 13:20 UTC, closed without merging

2023-03-06 13:21 UTC, manojava-gk commented
Will create a new PR using new Image component