Service release process step 1 to 4 added
catenax-ng/tx-portal-frontend pull request #231
Opened 2023-03-01 06:34 UTC by manojava-gk

2023-03-02 19:51 UTC, jjeroch requested changes

2023-03-02 19:51 UTC, jjeroch commented on cx-portal/src/assets/locales/de/servicerelease.json
> +    "defaultCardServiceImageAlt": "Part Chain",
Lets not take real data - please change to "{Service Name}" - same applies for Provider field

2023-03-02 19:51 UTC, jjeroch commented on cx-portal/src/assets/locales/en/servicerelease.json
> +    "images": "Image",
Please recheck, if thats the image part in the first step of the form; please use "Service Card Image" to ensure that its more clear for the user whats actually required/requested

2023-03-02 19:51 UTC, jjeroch commented on cx-portal/src/assets/locales/en/servicerelease.json
>      "longDescriptionDE": "Long Description (de)",
I am missing in the locale files the "Supporting Documents" as per the jira ticket

2023-03-02 19:51 UTC, jjeroch commented on cx-portal/src/components/pages/ServiceReleaseProcess/components/index.tsx
> +      headerTitle={t('submitApp.headerTitle')}
@manojava-gk please recheck the section - does it make sense to call it "APP" in row 62 to 67

2023-03-03 05:19 UTC, manojava-gk commented on cx-portal/src/assets/locales/en/servicerelease.json
>      "max3Images": "Max. 3 Images are supported",
This is meant for service release section. I have copied everything from appRelease section. Will remove unwanted key value pair

2023-03-03 05:32 UTC, manojava-gk commented on cx-portal/src/components/pages/ServiceReleaseProcess/components/index.tsx
> +      headerTitle={t('submitApp.headerTitle')}
These are some keys that has been copied from main.json. Noted. Will update this

2023-03-03 05:35 UTC, manojava-gk commented on cx-portal/src/assets/locales/en/servicerelease.json
>      "longDescriptionDE": "Long Description (de)",
Noted

2023-03-06 06:12 UTC, manojava-gk commented
@jjeroch Could you pls review this again?

2023-03-06 08:26 UTC, oyo requested changes
Disabling eslinter rules can be acceptable in some rare cases but it's now becoming a common pattern in your code. Also it's no good practice to implement a lot of logic in a chain of useEffects. Folders should never be called `CommonFiles` and services not `CommonService` because it doesn't say anything about the purpose of the code in it.

2023-03-06 08:26 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
> +                  )}`,
this doesn't make any sense - reading configuration values from language files?

2023-03-06 08:26 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/ContractAndConsent/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
we need to stop this practice disabling eslinter rules in useEffect

2023-03-06 08:26 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/ContractAndConsent/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
we need to stop this practice disabling eslinter rules in useEffect

2023-03-06 08:26 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
we need to stop this practice disabling eslinter rules in useEffect

2023-03-06 08:26 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
we need to stop this practice disabling eslinter rules in useEffect

2023-03-06 13:44 UTC, manojava-gk commented
@oyo As discussed with you over the call, multiple useEffects and eslinter disable code is not added in this PR. I have just created a wrapper component and moved all files to a specific folder.

2023-03-06 15:47 UTC, oyo approved these changes
as discussed approved for now because most of it was existing code. We are going to address the issues with a follow up ticket

2023-03-07 07:21 UTC, jjeroch approved these changes

2023-03-07 07:59 UTC, merged