Feature/cplp 2061/privacy policy
catenax-ng/tx-portal-frontend pull request #274
Opened 2023-03-20 08:00 UTC by lavanya-bmw

2023-03-20 09:22 UTC, oyo requested changes
Please replace the privacy policy string everywhere with the existing PrivacyPolicyType.
https://github.com/catenax-ng/tx-portal-frontend/blob/dev/cx-portal/src/features/adminBoard/adminBoardApiSlice.ts#L29-L35

When we have return types that come as string from API but are not arbitrary please define and use enum types like here:

```export enum PrivacyPolicyType {
  COMPANY_DATA = 'COMPANY_DATA',
  USER_DATA = 'USER_DATA',
  LOCATION = 'LOCATION',
  BROWSER_HISTORY = 'BROWSER_HISTORY',
  NONE = 'NONE',
}```

this will reduce possible errors in case of a typo and also help developing because the IDE will suggest the possible values

2023-03-20 09:22 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
> +                  getValuesPrivacyPolicies[0] === 'NONE'
Replace `NONE` with `PrivacyPolicyType.NONE`

2023-03-20 12:44 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
> +  const selectPrivacyPolicies = (policy: string, select: boolean) => {
`string` -> `PrivacyPolicyType

2023-03-20 12:45 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
> +  privacyPolicies: string[] | []
`string` -> `PrivacyPolicyType`

2023-03-21 05:00 UTC, lavanya-bmw commented
> Please replace the privacy policy `string` everywhere with the existing `PrivacyPolicyType`. https://github.com/catenax-ng/tx-portal-frontend/blob/dev/cx-portal/src/features/adminBoard/adminBoardApiSlice.ts#L29-L35
> 
> I haven't commented on each occurrence. As a general rule when we have return types coming as string from API that are not arbitrary but a distinct set of values please define and use enum types in the apiSlice like here:
> 
> ```
> export enum PrivacyPolicyType {
>   COMPANY_DATA = 'COMPANY_DATA',
>   USER_DATA = 'USER_DATA',
>   LOCATION = 'LOCATION',
>   BROWSER_HISTORY = 'BROWSER_HISTORY',
>   NONE = 'NONE',
> }
> ```
> 
> this will reduce possible errors in case of a typo and also help developing because the IDE will suggest the possible values

As discussed, since the privacy policies are fetched from API, I'm not defining static enums.

2023-03-21 07:15 UTC, oyo approved these changes

2023-03-21 07:16 UTC, merged