New feature service management added
catenax-ng/tx-portal-frontend pull request #287
Opened 2023-03-24 07:13 UTC by manojava-gk

2023-03-24 08:27 UTC, oyo requested changes
please convert the hard coded string to a const or enum type

2023-03-24 08:27 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx
> +        buttonLabel === 'saveAndProceed' &&
was there before but please fix and create a const or enum type for this

2023-03-24 08:27 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx
> +          buttonLabel === 'saveAndProceed' &&
please convert to const or enum type

2023-03-24 08:27 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx
> +      buttonLabel === 'saveAndProceed' &&
const or enum type

2023-03-24 08:27 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
> +            buttonLabel === 'saveAndProceed' &&
const or enum type

2023-03-26 20:27 UTC, jjeroch commented
@manojava-gk  can you please check the pr name. It will be tough for anyone to know what is inside. I suggest to update the name to something more meaningful and keep the connection to the "Service Release Process"

2023-03-27 05:14 UTC, oyo approved these changes
looks good now :)

2023-03-27 05:20 UTC, merged