Cleanups - Technical user
catenax-ng/tx-portal-frontend pull request #29
Opened 2022-12-14 07:58 UTC by manojava-gk

2022-12-14 10:14 UTC, manojava-gk commented on cx-portal/src/components/overlays/ServerResponse/index.tsx
> +  handleCallback?: any
thats the code smell issue. We can not use arrow functions in the props

2022-12-14 10:17 UTC, nidhigarg-bmw commented on cx-portal/src/components/overlays/ServerResponse/index.tsx
> +  handleCallback?: any
okay then rest fine for you. Will approve it now

2022-12-14 10:17 UTC, nidhigarg-bmw approved these changes

2022-12-14 10:30 UTC, manojava-gk commented on cx-portal/src/components/overlays/ServerResponse/index.tsx
> +  handleCallback?: any
This change was needed when I replaced the arrow with normal function. Now this is not needed.

2022-12-14 22:26 UTC, jjeroch requested changes
Small changes only, rest looks good

2022-12-14 22:26 UTC, jjeroch commented on CHANGELOG.md
> +   * Technical user
Please move this into the "Unreleased" area, thanks :)

2022-12-14 22:26 UTC, jjeroch commented on cx-portal/src/assets/locales/en/main.json
> +      "technicalUserSubheadlineError": "Something went wrong. We are looking to it",
Lets change this to:
"Something went wrong. The technical user did not got created due to a system error. Please try it later again or contact your administrator."

2022-12-16 09:57 UTC, oyo approved these changes

2022-12-19 13:33 UTC, oyo approved these changes
lgtm

2022-12-19 15:05 UTC, jjeroch submitted a review, later dismissed

2022-12-19 15:07 UTC, jjeroch commented
@oyo I cleaned up the conflict. Could you please approve once again?

2022-12-19 15:07 UTC, jjeroch approved these changes

2022-12-19 15:08 UTC, jjeroch commented
> @oyo I cleaned up the conflict. Could you please approve once again?


sorry just released that it isnt needed; i can already merge

2022-12-19 15:08 UTC, merged