Show loader icon on save action
catenax-ng/tx-portal-frontend pull request #298
Opened 2023-03-28 11:07 UTC by manojava-gk

2023-03-29 03:49 UTC, lavanya-bmw submitted a review, later dismissed
lgtm

2023-03-29 03:56 UTC, oyo requested changes
`setLoading(false)` often seen in both try/then and catch blocks. Please put after both to reduce duplicates

2023-03-29 03:56 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +          setLoading(false)
`setLoading(false)` in both `send` and `catch` clause - it can be put after both

2023-03-29 03:56 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
>      }
looks like `setLoading(false)` is set in almost all cases, only exception when result is not a string - is that the desired behavior?

2023-03-29 03:56 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
> +      setLoading(false)
again `setLoading(false)` in both try and catch clause - it can be put after both

2023-03-29 03:58 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx
>      } catch (error: any) {
old code but better use `unknown` instead of `any` for errors

2023-03-29 05:35 UTC, manojava-gk commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
>      }
setLoading is set to true when api action begins and to false after the response(success/error)

2023-03-30 05:20 UTC, oyo requested changes
one tiny remark

2023-03-30 05:20 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +      setLoading(false)
still the `if` and the `else` clause end with `setLoading(false)` - so just remove line 389 and 404 and place it after the closing else bracket

2023-03-30 05:58 UTC, oyo approved these changes

2023-03-30 05:59 UTC, merged