Feature/cplp 2061/app details privacy policy
catenax-ng/tx-portal-frontend pull request #301
Opened 2023-03-29 06:38 UTC by lavanya-bmw

2023-03-29 07:25 UTC, manojava-gk reviewed
Data type issue

2023-03-29 07:25 UTC, manojava-gk commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +        ? data.useCaseCategory?.map((item: any) => item.id)
Do not use `any`

2023-03-30 02:54 UTC, oyo requested changes
some remarks

2023-03-30 02:54 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +      })
when the only statement of an arrow function is return we can simplify this easier to read as:
`data.useCaseCategory.some((value) => typeof value === object`

2023-03-30 02:54 UTC, oyo commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +      contactNumber: appStatusData?.contactNumber || '',
for default values the use of `??` is preferred over `||`

2023-03-30 05:08 UTC, lavanya-bmw commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +  privacyPolicies: string[] | []
Done

2023-03-30 05:09 UTC, lavanya-bmw commented on cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
> +      contactNumber: appStatusData?.contactNumber || '',
Done

2023-03-30 05:14 UTC, oyo approved these changes

2023-03-30 05:16 UTC, merged