bugfix/cplp 2064/idp cleanup
catenax-ng/tx-portal-frontend pull request #307
Opened 2023-03-30 12:16 UTC by oyo

2023-03-30 14:00 UTC, lavanya-bmw requested changes
idp.json for german translations to be added

2023-03-30 14:03 UTC, lavanya-bmw commented on cx-portal/src/components/overlays/CXValidatingOverlay/ValidatingInput.tsx
> +
Commented code can be removed?

2023-03-30 14:07 UTC, lavanya-bmw requested changes

2023-03-30 14:07 UTC, lavanya-bmw commented on cx-portal/src/components/overlays/UpdateIDP/UpdateIDPContent.tsx
> +          }}
Console can be removed and validate can be: validate={(expr) => isWellknownMetadata(expr) }

2023-03-30 15:12 UTC, lavanya-bmw commented
> idp.json for german translations to be added

Added

2023-03-31 04:26 UTC, lavanya-bmw submitted a review, later dismissed
As discussed, Martin will work on duplication of code later

2023-03-31 06:32 UTC, jjeroch commented
Findings are all added in ticket https://jira.catena-x.net/browse/CPLP-2465

2023-03-31 06:45 UTC, manojava-gk commented
Just to avoid duplication. Created new MyForm component.

2023-03-31 06:45 UTC, lavanya-bmw approved these changes

2023-03-31 06:45 UTC, merged