UI fixes
catenax-ng/tx-portal-frontend pull request #31
Opened 2022-12-14 14:55 UTC by manojava-gk

2022-12-14 22:23 UTC, jjeroch requested changes

2022-12-14 22:23 UTC, jjeroch commented on cx-portal/src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
> +          <Typography variant="body1" sx={{ fontSize: '16px' }}>
@manojava-gk logical question:
why do we need to add `fontSize: '16px'` if we already mention `variant="body1`

2022-12-14 22:23 UTC, jjeroch commented on cx-portal/src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
> +        <Typography variant="body1" sx={{ fontSize: '16px' }}>
same comment as above

2022-12-14 22:23 UTC, jjeroch commented on cx-portal/src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
> +          {row.type === 'COMPANY_CONNECTOR' ? 'Owned' : 'Managed'}
Suggesting to already enable translation with the locales files

2022-12-15 05:42 UTC, manojava-gk commented on cx-portal/src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
> +          <Typography variant="body1" sx={{ fontSize: '16px' }}>
It was needed bcz ```body1``` has ```fontSize 18px```. But now you have merged Typography changes to dev, I can use other variants

2022-12-15 05:42 UTC, manojava-gk commented on cx-portal/src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
> +          {row.type === 'COMPANY_CONNECTOR' ? 'Owned' : 'Managed'}
will move this

2022-12-16 09:45 UTC, oyo requested changes

2022-12-16 09:45 UTC, oyo commented on cx-portal/src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
> +          )}
write this with less duplication as
`<LockIcon sx={{ color: row.dapsRegistrationSuccessful ? 'green' : '#b6b6b6' }} />`

2022-12-16 09:45 UTC, oyo commented on cx-portal/src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
> +        </Box>
Wrapping this in a <Box> seems unnecessary - the next `renderCell` below goes without it

2022-12-19 07:15 UTC, oyo approved these changes
looks good from my side now

2022-12-20 07:08 UTC, jjeroch approved these changes

2022-12-20 07:19 UTC, merged