add placehlders if no app access
catenax-ng/tx-portal-frontend pull request #32
Opened 2022-12-15 13:00 UTC by nidhigarg-bmw

2022-12-16 09:28 UTC, oyo requested changes
translation dependency and merge conflict

2022-12-16 09:28 UTC, oyo commented on cx-portal/src/components/shared/frame/UserList/index.tsx
> +              t(sectionTitle) === 'Identity Management'
never check for a translation value
1. doesn't work for other languages than english
2. will break when the text changes

2022-12-16 14:11 UTC, nidhigarg-bmw commented on cx-portal/src/components/shared/frame/UserList/index.tsx
> +              t(sectionTitle) === 'Identity Management'
@oyo Made the changes. Please review again

2022-12-19 04:23 UTC, oyo approved these changes
looks good now

2022-12-19 07:15 UTC, oyo approved these changes

2022-12-19 07:22 UTC, merged