Business Logic & API: Document Endpoint Get and PUT PNG/JPEG
catenax-ng/tx-portal-frontend pull request #33
Opened 2022-12-19 06:32 UTC by lavanya-bmw

2022-12-19 07:25 UTC, oyo requested changes

2022-12-19 07:25 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +  }, [fetchAppStatus])
what's the reason why this eslint rule got disabled?

2022-12-19 07:25 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/ValidateAndPublish/index.tsx
> +                    )[0]?.shortDescription
can you please change this entire logic to:
`description={`
`  appStatusData?.descriptions?.filter(`
`    (lang: { languageCode: string }) => lang.languageCode === i18next.language`
`)}`

2022-12-20 07:10 UTC, jjeroch commented
cleaned up the changelog

2022-12-20 07:10 UTC, jjeroch commented
2 comments left from martin

2022-12-21 08:55 UTC, oyo approved these changes
looks good now

2022-12-21 11:07 UTC, merged