Feature/cplp 2142/add status subscription
catenax-ng/tx-portal-frontend pull request #337
Opened 2023-04-05 13:27 UTC by nidhigarg-bmw

2023-04-06 05:38 UTC, manojava-gk reviewed
Type and Component behaviour

2023-04-06 05:38 UTC, manojava-gk commented on cx-portal-shared-components/src/components/basic/OrderStatusButton/index.tsx
> +      {fetchButton(4, buttonStyle.background1, status === 'INACTIVE', {
Why not a loop?

2023-04-06 05:38 UTC, manojava-gk commented on cx-portal-shared-components/src/components/basic/OrderStatusButton/index.tsx
> +          background1: '#f5f9ee',
same color codes are being used in multiple places. Better to move them to theme file or create a enum or const in the component itself

2023-04-06 05:38 UTC, manojava-gk commented on cx-portal/src/features/apps/apiSlice.ts
> +        data.forEach(async (appItem: any) => {
Can avoid any?

2023-04-06 05:38 UTC, manojava-gk commented on cx-portal/src/features/apps/apiSlice.ts
> +        const data: any = activeApps.data
Can avoid any?

2023-04-06 05:39 UTC, oyo requested changes

2023-04-06 05:39 UTC, oyo commented on cx-portal/src/features/apps/apiSlice.ts
> +        const data: any = activeApps.data
we know the data type from the api endpoint here: https://portal-swagger.dev.demo.catena-x.net/?urls.primaryName=Portal%20App%20Marketplace%20API#/Apps/get_api_Apps_active
don't we have a type for this defined? please define and use

2023-04-06 05:39 UTC, oyo commented on cx-portal/src/features/apps/apiSlice.ts
> +        const subscriptionData: any = subscriptionStatus.data
please define and use type

2023-04-07 02:12 UTC, oyo submitted a review, later dismissed
looks good to me now

2023-04-10 06:55 UTC, manojava-gk approved these changes
looks okay now

2023-04-10 06:56 UTC, merged