Change/company role introduction page
catenax-ng/tx-portal-frontend pull request #4
Opened 2022-11-29 21:17 UTC by jjeroch

- [x] Update card typo variant
- [x] Update participant background color
- [ ] .topFlexContainer add padding (padding: 90px 0px)
- [ ] add margin between .topFlexContainer and section start => 112px
- [ ] text container description needs to be on the same height for cardWithImage elements (for headlines with 1 line and 2 lines)
- [ ]  text container description needs to be on the same height for cardWithoutImage elements (for headlines with 1 line and 2 lines)
- [ ] image inside the cardWithImage element => sizing update needed (height 156px; width 272px)
- [x] add details instead of "read more" for the cardWithoutImage

2022-11-29 21:20 UTC, jjeroch commented
@manojava-gk i did run through the company role introduction development and started a new branch. Inside the PR you can find all findings / tasks which still need to get "fixed".
Can you please run through them

2022-11-30 05:47 UTC, manojava-gk commented
> @manojava-gk i did run through the company role introduction development and started a new branch. Inside the PR you can find all findings / tasks which still need to get "fixed". Can you please run through them

Sure will check the rest

2022-11-30 06:11 UTC, manojava-gk commented
> * text container description needs to be on the same height

Looks this part is impossible to achieve as it always try to fit with the adjacent box. In my opinion we can only make sure of aligning top and bottom texts(Title and Details) but not the description.

Will take opinion from other team members as well for this.

2022-11-30 06:13 UTC, manojava-gk commented
> * image inside the cardWithImage element => sizing update needed (height 156px; width 272px)

Not a great idea to fix the image size here(especially both height and width). Allowing them to fit with the box layout makes more sense to me

2022-11-30 11:23 UTC, manojava-gk commented
All done :)

2022-11-30 18:34 UTC, jjeroch commented
@manojava-gk  I can only merge if it got approved from your side since I have created the pr. Can you approve please. I ahve checked your changes and they are fine for me :)

2022-12-01 04:40 UTC, oyo requested changes
some remarks mostly on css properties

2022-12-01 04:40 UTC, oyo commented on cx-portal/src/components/pages/CompanyRoles/CompanyRoles.scss
> +  padding: 0px 80px;
not critical but for zero it is better to go without unit: `0px` -> `0`

2022-12-01 04:40 UTC, oyo commented on cx-portal/src/components/pages/CompanyRoles/components/Cards/Card.tsx
> +            display: '-webkit-box',
what is the purpose of this? `-webkit-box` looks browser dependent and not a valid display property:
Specification: https://w3c.github.io/csswg-drafts/css-display/#the-display-properties

Did you mean `block` ?

2022-12-01 04:40 UTC, oyo commented on cx-portal/src/components/pages/CompanyRoles/components/Cards/Card.tsx
> +            display: '-webkit-box',
see comment line above

2022-12-01 04:40 UTC, oyo commented on cx-portal/src/components/pages/CompanyRoles/components/Cards/Card.tsx
> +            WebkitBoxOrient: 'vertical',
we should try to go without browser specific properties because there are some non-webkit browsers in use and we might get unreliable results on other browsers:
https://gs.statcounter.com/browser-market-share
better use `boxOrient` - but it is non standard: https://developer.mozilla.org/en-US/docs/Web/CSS/box-orient

2022-12-01 04:40 UTC, oyo commented on cx-portal/src/components/pages/CompanyRoles/components/Cards/Card.tsx
> +            WebkitBoxOrient: 'vertical',
see comment above

2022-12-01 04:40 UTC, oyo commented on cx-portal/src/components/pages/CompanyRoles/components/Cards/CardWithImage.tsx
> +              : '156px',
the purpose of this is not easy to understand. In this case an inline comment might make sense to briefly explain the logic.

2022-12-01 06:09 UTC, manojava-gk approved these changes
lgtm

2022-12-01 06:14 UTC, manojava-gk commented on cx-portal/src/components/pages/CompanyRoles/components/Cards/CardWithImage.tsx
> +              : '156px',
will add a comment

2022-12-01 06:26 UTC, manojava-gk commented on cx-portal/src/components/pages/CompanyRoles/components/Cards/Card.tsx
> +            display: '-webkit-box',
I want to show dots if the title or description is going beyond 1 or 2 lines respectively.

![image](https://user-images.githubusercontent.com/111366021/204981045-e2d1dac8-aaae-4cd9-b9d3-68c1e1b32d2c.png)

2022-12-01 06:27 UTC, manojava-gk commented on cx-portal/src/components/pages/CompanyRoles/components/Cards/Card.tsx
> +            display: '-webkit-box',
https://css-tricks.com/almanac/properties/l/line-clamp/

this is where I found a solution for my requirement

2022-12-01 08:43 UTC, oyo approved these changes
okay now

2022-12-01 08:48 UTC, merged