Feature/cplp 1544/app subscription page
catenax-ng/tx-portal-frontend pull request #49
Opened 2022-12-21 13:13 UTC by nidhigarg-bmw

2022-12-22 04:30 UTC, oyo requested changes
see comments

2022-12-22 04:30 UTC, oyo commented on cx-portal/src/components/overlays/ActivateSubscription/index.tsx
> +                <hr />
try to avoid `<hr>`, because it is usually a styling element which you can easily implement in css where styling elements belong. Here you can simply achieve the line with a css rule:
`li:first-child { border-bottom: ...`

2022-12-22 04:30 UTC, oyo commented on cx-portal/src/components/overlays/ActivateSubscription/index.tsx
> +            </div>
I see many redundant HTML nodes here. Use <div> only when there is no other option. The DOM tree should reflect the document structure and this should be kept free of redundant items whenever possible. You also don't need `className` for most of the child items. Here you can simply go with:

`<DialogContent>`
`  <ul className="activationSubscription">`
`    <li>`
`      <div>...</div>`
`      <div>...</div>`
`...`

then create css rules - instead of `.item`, `.firstSection` and `.middleSection` use css selectors: 

`.activationSubscription {`
`  li {`
`    div:first-child {...}`
`    div:last-child {...}`
`  }`
`}`

maybe even possible to avoid the divs wrapping the `Typography` but haven't tried that

2022-12-22 04:30 UTC, oyo commented on cx-portal/src/components/overlays/ActivateSubscription/index.tsx
> +              <div className="URLInput">
What's the reason for the two nested divs?

2022-12-22 04:30 UTC, oyo commented on cx-portal/src/components/overlays/ActivateSubscription/index.tsx
> +              onCloseWithIcon: () => dispatch(show(OVERLAYS.NONE, '')),
use `dispatch(closeOverlay())`

2022-12-22 04:30 UTC, oyo commented on cx-portal/src/components/overlays/ActivateSubscription/index.tsx
> +              Close
translations?

2022-12-22 04:30 UTC, oyo commented on cx-portal/src/components/overlays/ActivateSubscription/index.tsx
> +              onClick={() => dispatch(show(OVERLAYS.NONE, ''))}
`dispatch(closeOverlay())`

2022-12-22 04:30 UTC, oyo commented on cx-portal/src/components/overlays/ActivateSubscription/index.tsx
> +              Close
translations

2022-12-22 04:30 UTC, oyo commented on cx-portal/src/components/overlays/ActivateSubscription/index.tsx
> +              Confirm
translations

2022-12-22 04:30 UTC, oyo commented on cx-portal/src/components/pages/AppStore/SubscriptionElements.tsx
> +                        <div className="item">
again too many nested nodes for no reason. Eliminate the divs. Also no need for the `return`s here when there is no other logic in the arrow functions,.

2022-12-22 13:21 UTC, nidhigarg-bmw commented
@oyo I made all the changes you mentioned, can you please review again

2022-12-28 10:18 UTC, oyo approved these changes
lgtm

2022-12-28 10:44 UTC, merged