Feature/cplp 1494/service marketplace updates
catenax-ng/tx-portal-frontend pull request #6
Opened 2022-12-01 12:40 UTC by nidhigarg-bmw

2022-12-01 12:48 UTC, manojava-gk commented on cx-portal-shared-components/src/components/content/Cards/CardHorizontal.tsx
> +        {/* <Typography
If not needed, kindly remove commented lines

2022-12-01 12:50 UTC, nidhigarg-bmw commented on cx-portal-shared-components/src/components/content/Cards/CardHorizontal.tsx
> +        {/* <Typography
Yeah already did and also fixed the code smells

2022-12-01 13:22 UTC, manojava-gk requested changes
Majorly in Cards component

2022-12-01 13:22 UTC, manojava-gk commented on cx-portal-shared-components/src/components/content/Cards/CardHorizontal.tsx
> -            overflow: 'hidden',
Any reason for removing this? and looks browser support for `display: box, lineClamp: '2' & boxOrient: 'vertical'` has been deprecated.
@oyo I tried this instead of `web-kit` but not working.

2022-12-01 13:22 UTC, manojava-gk commented on cx-portal-shared-components/src/components/content/Cards/CardHorizontal.tsx
> -        <Box p={1} display="flex" justifyContent="space-between">
same here. Any reason to remove this?

2022-12-01 23:08 UTC, jjeroch requested changes

2022-12-01 23:08 UTC, jjeroch commented on cx-portal/src/components/pages/ServiceMarketplace/ServiceMarketplace.scss
> +    font-size: 36px;
@nidhigarg-bmw can we use the headline parameter instead of setting the font_size manually?

2022-12-01 23:08 UTC, jjeroch commented on cx-portal/src/components/pages/ServiceMarketplaceDetail/components/MarketplaceDocuments/index.tsx
> +        <Typography variant="h4">
@nidhigarg-bmw should be "h3" if this is the document headline

2022-12-01 23:08 UTC, jjeroch commented on cx-portal/src/components/pages/ServiceMarketplace/index.tsx
> +          <Typography className="newServicesTitle" variant="h5">
are we sure that "h5" is correct. Looks for me like the headline which is "h2"

2022-12-01 23:08 UTC, jjeroch commented on cx-portal-shared-components/src/components/content/Cards/CardHorizontal.tsx
> +          variant="h6"
@nidhigarg-bmw why "h6" now? As per the design its saying "h4"

2022-12-01 23:08 UTC, jjeroch commented on cx-portal/src/components/pages/ServiceMarketplace/index.tsx
> +  }
likely update needed due to the update inside the translation files

2022-12-02 07:31 UTC, nidhigarg-bmw commented
@manojava-gk For cardHorizontal, this card is not using somewhere else. So these changes will not affect any of other files :)

2022-12-02 07:32 UTC, manojava-gk commented
> Majorly in Cards component

got confused with Cards and CardHorizontal component. @nidhigarg-bmw clarified that variant option with CardHorizontal is not in use anywhere else. So marking them as resolved

2022-12-02 07:39 UTC, nidhigarg-bmw commented
@jjeroch  Made the changes. Please review again

2022-12-02 12:53 UTC, manojava-gk approved these changes

2022-12-05 20:19 UTC, jjeroch approved these changes

2022-12-06 05:57 UTC, merged