Update static templates CPLP-1994
catenax-ng/tx-portal-frontend pull request #99
Opened 2023-01-16 10:33 UTC by manojava-gk

2023-01-18 23:43 UTC, jjeroch requested changes

2023-01-18 23:43 UTC, jjeroch commented on CHANGELOG.md
> +   * Update Dailog header font size to 24px
@manojava-gk thats already released in the released version below if I am not wrong. Please have a look into ## 1.0.0-RC2

2023-01-18 23:43 UTC, jjeroch commented on CHANGELOG.md
> +* Bugfix - Change Email Pattern Regex to fix Hostspot
same as above

2023-01-18 23:43 UTC, jjeroch commented on CHANGELOG.md
> +   * Remove asset repo dependency. New api to get image
same as above

2023-01-18 23:44 UTC, jjeroch commented
content wise it looks good - exactly what I was looking for.
It is off course a bit awkward that we locate now the full template inside the locales; but I like the solution much more then having it placed inside the page code. Also it provides the chance to have multi language even for the pictures - which is very good

2023-01-19 07:34 UTC, oyo requested changes

2023-01-19 07:34 UTC, oyo commented on cx-portal-shared-components/src/components/basic/StaticTemplate/Cards/TextCenterAlignedBody2.tsx
> +        </Typography>
almost same block repeated three times
please change to:
`[provider.subTitle1, provider.subTitle2, provider.subTitle3].map(`
`  (title: string) => <Typography etc>{title}</Topography>`
`)`

2023-01-23 07:04 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/CompanyRoles/index.tsx
> +  const [companyRoles, setCompanyRoles] = useState<any>()
fix this datatype

2023-01-23 07:04 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/UseCase/index.tsx
> +    CommonService.getUseCases((data: any) => {
any datatype

2023-01-23 07:30 UTC, manojava-gk commented on cx-portal/src/components/pages/CompanyRoles/index.tsx
> +  const [companyRoles, setCompanyRoles] = useState<any>()
it has to be any :)

2023-01-23 07:30 UTC, manojava-gk commented on cx-portal/src/components/pages/UseCase/index.tsx
> +    CommonService.getUseCases((data: any) => {
it has to be any :)

2023-01-23 07:36 UTC, oyo approved these changes
lgtm now

2023-01-23 07:53 UTC, jjeroch approved these changes

2023-01-23 07:54 UTC, merged